### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by Dwarben** [BlenderDefender/Gizmodal-Ops#17]
**Describe the bug**
to speed up my work I am implementing pie menus. When I go to activate 'tab for pie menu' the addon stops working and to reactivate it I must first deactivate it 

**To Reproduce**

- with active gizmodal-Ops 
1) Go to blender preferences
2) go to the keymap section
3) under "3d View" activate "tab for pie menu".

**Expected behavior**
the addon stops working, remaining on the last operation performed 

**Video of the bug**

https://github.com/BlenderDefender/Gizmodal-Ops/assets/164523081/e80c113d-0333-4fef-8473-3b130e1769ba

**System Information (please complete the following information):**
- Windows 10
- Blender Version: 4.1
- Addon Version: 1.0.1 (debug version)

**Comment by BlenderDefender** [comment]
@Dwarben Could you please add a proper title for this bug report? If there's no descriptive title, I don't know what an issue is about, which reduces the likelyhood of an issue being worked on. Apart from that, if you're already using the debug version, it would be great if you could share the log output from this file:
```
%HOMEPATH%/GizmodalOpsLog.txt
```

A similar issue to this was reported a while ago (see #15), so I'll have a look at is soon.

**Comment by Dwarben** [comment]
Anyway, I've just got home, turned on blender and everything seems to be working properly... I can't explain why. anyway, I'll attach the log output anyway, maybe there's something there that can be useful for the future. tell me if I'll leave the issue or put it as resolved 

Starting up Gizmodal Ops
Gizmodal Ops Register - Warning: Key 3D View not found.
Gizmodal Ops Register - Warning: Key Pose not found.
Gizmodal Ops Register - Warning: Key Object Mode not found.
Gizmodal Ops Register - Warning: Key Curve not found.
Gizmodal Ops Register - Warning: Key Curves not found.
Gizmodal Ops Register - Warning: Key Mesh not found.
Gizmodal Ops Register - Warning: Key Armature not found.
Gizmodal Ops Register - Warning: Key Metaball not found.
Gizmodal Ops Register - Warning: Key Lattice not found.
Gizmodal Ops Register - Warning: Key UV Editor not found.

**Comment by BlenderDefender** [comment]
@Dwarben Alright, I think I know what the cause of the issue is. To prove my hypothesis, I've made another debug version, [GizmodalOpsDebug17_01.zip](https://github.com/BlenderDefender/Gizmodal-Ops/files/14968159/GizmodalOpsDebug17_01.zip). Here's what I'd like you to try out:
1. Disable "Tab for Pie Menu"
2. Install this version and make sure it's working correctly
3. Enable "Tab for Pie Menu"
4. Gizmodal Ops shouldn't be working now. Head to `Preferences > Addons > Gizmodal Ops` and click on the refresh button there.
5. Gizmodal Ops should be working again. Regardless of whether or not that's the case, the log output (same file as before) would be really helpful.

From my personal testing, everything should work as described. I've also found out this bug occurs in older Blender versions as well.

**Comment by Dwarben** [comment]
I followed the directions you gave me but it still doesn't work.


log output

Starting up Gizmodal Ops
Gizmodal Ops Register - Warning: Key 3D View not found.
Gizmodal Ops Register - Warning: Key Pose not found.
Gizmodal Ops Register - Warning: Key Object Mode not found.
Gizmodal Ops Register - Warning: Key Curve not found.
Gizmodal Ops Register - Warning: Key Curves not found.
Gizmodal Ops Register - Warning: Key Mesh not found.
Gizmodal Ops Register - Warning: Key Armature not found.
Gizmodal Ops Register - Warning: Key Metaball not found.
Gizmodal Ops Register - Warning: Key Lattice not found.
Gizmodal Ops Register - Warning: Key UV Editor not found.
Starting up Gizmodal Ops
Gizmodal Ops Register - Warning: Key 3D View not found.
Gizmodal Ops Register - Warning: Key Pose not found.
Gizmodal Ops Register - Warning: Key Object Mode not found.
Gizmodal Ops Register - Warning: Key Curve not found.
Gizmodal Ops Register - Warning: Key Curves not found.
Gizmodal Ops Register - Warning: Key Mesh not found.
Gizmodal Ops Register - Warning: Key Armature not found.
Gizmodal Ops Register - Warning: Key Metaball not found.
Gizmodal Ops Register - Warning: Key Lattice not found.
Gizmodal Ops Register - Warning: Key UV Editor not found.

**Comment by BlenderDefender** [comment]
> I followed the directions you gave me but it still doesn't work. but if I restart blender everything seems to work
> 
> log output
> ...

Are you sure that you've used the right version? The log output doesn't look like it.
So please download the correct version, uninstall the previous version, restart Blender and follow the steps I've written about in the previous comment.

**Comment by Dwarben** [comment]
I'm sure, to be on the safe side I re-downloaded the version you gave me and tried it again and, as I said, it only works when I restart Blender.

**Comment by BlenderDefender** [comment]
Oh, I think I've expressed myself in a confusing way, I'm not talking about the refresh button at the bottom left, I'm talking about a refresh button within the Gizmodal Ops preferences, see this picture:
![grafik](https://github.com/BlenderDefender/Gizmodal-Ops/assets/61777131/f22a2795-7ab9-4421-bb68-c99847df2b78)

I'm sorry for this misunderstanding. It would be great, if you could test it again using this button there.

**Comment by BlenderDefender** [comment]
@Dwarben Alright then, I'll try to implement a fix as soon as possible, thanks for your assistance

**Comment by junkyung09** [comment]
Hello, I have a question, so I'm leaving a comment.

Currently, this add-on is not functioning at all on the uv screen.

If you check the picture below, press rotation (R), press the y-axis with the keyboard, and the number 90 into the number pad keyboard to reduce the scale value.

I set it up in the key map as you told me above, and I also completed refreshing.

If you activate it, it looks like the attached picture, and if you deactivate it, it rotates well.
When disabled, the g, s, and r keys do not work in edit mode or object mode

The blender version you are using is 4.3.

![Image](https://github.com/user-attachments/assets/06280000-97da-4b31-9249-0bfd5a7178f5)

![Image](https://github.com/user-attachments/assets/16001bec-f1d4-4319-8b17-62fe5a2166bf)
